language: ruby
rvm:
  - 1.9.3
  - 1.9.2
before_script:
  - echo "TEST"
  - export RAILS_2CH_SERVER_DATABASE_PASSWORD=`perl -le \'print map \{ ("a".."z", "A".."Z", 0..9)[rand 62] \} 1..253\'`
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('${RAILS_2CH_SERVER_DATABASE_PASSWORD}') WHERE user='rails';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - echo "CREATE DATABASE bbsdb;" | mysql -u root
  - echo "CREATE DATABASE bbsdb-test;" | mysql -u root
script:
  - echo ${RAILS_2CH_SERVER_DATABASE_PASSWORD}
  - bundle install
  - bundle exec rake db:schema:load RAILS_ENV=test
  - bundle exec rake db:fixtures:load RAILS_ENV=test
  - bundle exec rake spec
gemfile:
  - Gemfile
